levelOrder(root);
    // inOrder(root);
    // cout<<endl;
    // PreOrder(root);
    // cout<<endl;
    // postOrder(root);
    // cout<<endl;
    // minValue(root);
    // cout<<endl;
    // maxValue(root);